import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/card_model.dart';
import '../providers/portfolio_provider.dart';
import '../providers/auth_provider.dart';

class CardFormScreen extends StatefulWidget {
  final CardModel? initialData;

  const CardFormScreen({super.key, this.initialData});

  @override
  State<CardFormScreen> createState() => _CardFormScreenState();
}

class _CardFormScreenState extends State<CardFormScreen> {
  final _formKey = GlobalKey<FormState>();
  
  late TextEditingController _playerController;
  late TextEditingController _yearController;
  late TextEditingController _brandController;
  late TextEditingController _seriesController;
  late TextEditingController _insertController;
  late TextEditingController _parallelController;
  late TextEditingController _serialNumberController;
  late TextEditingController _purchasePriceController;
  late TextEditingController _currentValueController;
  late TextEditingController _gradeCompanyController;
  late TextEditingController _gradeValueController;

  Sport _selectedSport = Sport.basketball;
  bool _graded = false;
  bool _watchlist = false;
  Currency _currency = Currency.usd;

  @override
  void initState() {
    super.initState();
    final data = widget.initialData;
    _playerController = TextEditingController(text: data?.player ?? '');
    _yearController = TextEditingController(text: data?.year.toString() ?? '');
    _brandController = TextEditingController(text: data?.brand ?? '');
    _seriesController = TextEditingController(text: data?.series ?? '');
    _insertController = TextEditingController(text: data?.insert ?? '');
    _parallelController = TextEditingController(text: data?.parallel ?? '');
    _serialNumberController = TextEditingController(text: data?.serialNumber ?? '');
    _purchasePriceController = TextEditingController(text: data?.purchasePrice.toString() ?? '');
    _currentValueController = TextEditingController(text: data?.currentValue.toString() ?? '');
    _gradeCompanyController = TextEditingController(text: data?.gradeCompany ?? '');
    _gradeValueController = TextEditingController(text: data?.gradeValue ?? '');

    if (data != null) {
      _selectedSport = data.sport;
      _graded = data.graded;
      _watchlist = data.watchlist ?? false;
      _currency = data.currency;
    }
  }

  @override
  void dispose() {
    _playerController.dispose();
    _yearController.dispose();
    _brandController.dispose();
    _seriesController.dispose();
    _insertController.dispose();
    _parallelController.dispose();
    _serialNumberController.dispose();
    _purchasePriceController.dispose();
    _currentValueController.dispose();
    _gradeCompanyController.dispose();
    _gradeValueController.dispose();
    super.dispose();
  }

  Future<void> _saveCard() async {
    if (!_formKey.currentState!.validate()) return;

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final portfolioProvider = Provider.of<PortfolioProvider>(context, listen: false);

    final card = CardModel(
      id: widget.initialData?.id ?? '', // ID will be generated by backend if empty
      player: _playerController.text,
      year: int.tryParse(_yearController.text) ?? 0,
      sport: _selectedSport,
      brand: _brandController.text,
      series: _seriesController.text,
      insert: _insertController.text,
      parallel: _parallelController.text.isEmpty ? null : _parallelController.text,
      serialNumber: _serialNumberController.text.isEmpty ? null : _serialNumberController.text,
      graded: _graded,
      gradeCompany: _graded ? _gradeCompanyController.text : null,
      gradeValue: _graded ? _gradeValueController.text : null,
      currency: _currency,
      purchaseDate: widget.initialData?.purchaseDate ?? DateTime.now().toIso8601String(),
      purchasePrice: double.tryParse(_purchasePriceController.text) ?? 0.0,
      currentValue: double.tryParse(_currentValueController.text) ?? 0.0,
      priceHistory: widget.initialData?.priceHistory ?? [],
      sold: widget.initialData?.sold ?? false,
      watchlist: _watchlist,
    );

    try {
      if (widget.initialData == null) {
        await portfolioProvider.addCard(card, authProvider.getIdToken);
      } else {
        await portfolioProvider.updateCard(card, authProvider.getIdToken);
      }
      if (mounted) Navigator.pop(context);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error saving card: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.initialData == null ? 'Add Card' : 'Edit Card'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _saveCard,
          ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            TextFormField(
              controller: _playerController,
              decoration: const InputDecoration(labelText: 'Player Name'),
              validator: (value) => value!.isEmpty ? 'Required' : null,
              style: const TextStyle(color: Colors.white),
            ),
            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: _yearController,
                    decoration: const InputDecoration(labelText: 'Year'),
                    keyboardType: TextInputType.number,
                    validator: (value) => value!.isEmpty ? 'Required' : null,
                    style: const TextStyle(color: Colors.white),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: DropdownButtonFormField<Sport>(
                    value: _selectedSport,
                    decoration: const InputDecoration(labelText: 'Sport'),
                    dropdownColor: const Color(0xFF1E293B),
                    items: Sport.values.map((s) {
                      return DropdownMenuItem(
                        value: s,
                        child: Text(s.toString().split('.').last.toUpperCase(), style: const TextStyle(color: Colors.white)),
                      );
                    }).toList(),
                    onChanged: (v) => setState(() => _selectedSport = v!),
                  ),
                ),
              ],
            ),
            TextFormField(
              controller: _brandController,
              decoration: const InputDecoration(labelText: 'Brand (e.g. Prizm)'),
              validator: (value) => value!.isEmpty ? 'Required' : null,
              style: const TextStyle(color: Colors.white),
            ),
            TextFormField(
              controller: _seriesController,
              decoration: const InputDecoration(labelText: 'Series (e.g. Base)'),
              validator: (value) => value!.isEmpty ? 'Required' : null,
              style: const TextStyle(color: Colors.white),
            ),
            TextFormField(
              controller: _insertController,
              decoration: const InputDecoration(labelText: 'Insert (e.g. Rookie)'),
              validator: (value) => value!.isEmpty ? 'Required' : null,
              style: const TextStyle(color: Colors.white),
            ),
            TextFormField(
              controller: _parallelController,
              decoration: const InputDecoration(labelText: 'Parallel (Optional)'),
              style: const TextStyle(color: Colors.white),
            ),
            TextFormField(
              controller: _serialNumberController,
              decoration: const InputDecoration(labelText: 'Serial Number (Optional)'),
              style: const TextStyle(color: Colors.white),
            ),
            SwitchListTile(
              title: const Text('Graded', style: TextStyle(color: Colors.white)),
              value: _graded,
              onChanged: (v) => setState(() => _graded = v),
            ),
            if (_graded) ...[
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _gradeCompanyController,
                      decoration: const InputDecoration(labelText: 'Company (e.g. PSA)'),
                      style: const TextStyle(color: Colors.white),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _gradeValueController,
                      decoration: const InputDecoration(labelText: 'Grade (e.g. 10)'),
                      style: const TextStyle(color: Colors.white),
                    ),
                  ),
                ],
              ),
            ],
            const SizedBox(height: 16),
            const Divider(color: Colors.grey),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: _purchasePriceController,
                    decoration: const InputDecoration(labelText: 'Purchase Price'),
                    keyboardType: TextInputType.number,
                    style: const TextStyle(color: Colors.white),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: TextFormField(
                    controller: _currentValueController,
                    decoration: const InputDecoration(labelText: 'Current Value'),
                    keyboardType: TextInputType.number,
                    style: const TextStyle(color: Colors.white),
                  ),
                ),
              ],
            ),
            SwitchListTile(
              title: const Text('Watchlist', style: TextStyle(color: Colors.white)),
              value: _watchlist,
              onChanged: (v) => setState(() => _watchlist = v),
            ),
          ],
        ),
      ),
    );
  }
}
